### PR TITLE
Add broadcast option

### PR DESCRIPTION
**Pull request by hadleyrich**
Refs #9

It looks like the broadcast option added here:

https://github.com/spacemanspiff2007/PyArtNet/commit/6a4ef9d952aafe6a11f8f8dc63d8d782ed4a8d33

Has been lost along the way either due to refactor or on purpose. I needed this for something I was working on so thought I would contribute it back. If it's not wanted or if there's some other thing that I'm missing feel free to close out.

Thanks for the library :)

### CODE REVIEW

**Comment by spacemanspiff2007** [comment]
Thanks for the PR. Broadcast support was removed because of artnet v4 spec:

grafik

So I don't think it's a good idea to merge it again.

**Comment by hadleyrich** [comment]
> So I don't think it's a good idea to merge it again.

Makes sense, thanks for letting me know :)

**Comment by Breina** [comment]
If it helps, you are free to use multicast instead (still off-spec).

**Comment by hadleyrich** [comment]
Thanks to you both. I hadn't actually realised that I could use a directed broadcast to get around the socket permission issue so all good :)

**Pull request closed without merging**
